### ISSUE TITLE
Creare Visualizzazione

### ISSUE THREAD

**Issue by MindfulLearner** [project-bnb/BoolBnB-front#16]
Tenete conto di avere la pagina principale che si chiama app.vue

accendere backend e usare axios per il metodo GET url (http://ilvostrolink.test/api/apartments)

create tipo un componente e dentro app.vue e  dovra avere: 

Milestone 1: Creare un componente che mostra le card in tutta la pagina. Ogni card deve visualizzare le seguenti informazioni:

```json
{
  "user_id": ,
  "title": ,
  "rooms": ,
  "beds": ,
  "bathrooms": ,
  "square_meters": ,
  "address": ,
  "latitude": ,
  "longitude": ,
  "image": ,
  "is_visible":  
}
```

Milestone 2: Validare i campi obbligatori, ovvero tutti. 'is_visible' deve essere un booleano, quindi 0 o 1.

**Comment by surefire-hu** [comment]
crato cardlist collegato con il backend funzionante

**Comment by MindfulLearner** [comment]
nice
