### ISSUE TITLE
Creare Modifica

### ISSUE THREAD

**Issue by MindfulLearner** [project-bnb/BoolBnB-front#18]
Tenete conto di avere la pagina principale che si chiama app.vue

accendere backend e usare axios per il metodo PUT url http://ilvostrolink.test/api/apartments/{id}

create tipo un componente e dentro app.vue e  dovra avere: 

Milestone 1: Creare un componente per la modifica, dove ci sarà un form che invia i dati tramite PUT API al backend.

```json
{
  "user_id": ,
  "title": ,
  "rooms": ,
  "beds": ,
  "bathrooms": ,
  "square_meters": ,
  "address": ,
  "latitude": ,
  "longitude": ,
  "image": ,
  "is_visible":  
}
```

Milestone 2: Validare i campi obbligatori.

**Comment by salvatore-impellizzeri** [comment]
Creazione Pagina per le Modifiche completato. Ovviamente c'è da sistemare la parte esteticame come per la pagina di Creazione.
