### ISSUE TITLE
Creare Setup Route su VueJS

### ISSUE THREAD

**Issue by MindfulLearner** [project-bnb/BoolBnB-front#20]
--
Creare una pagina lobby in cui cliccando le varie sezioni si va sulla pagina che servono a quelle. Collegare le pagine create con le routes VueJS: Visualizzazione, Creazione, Modifica e Cancellazione.
--
Questa è la mia repo dove avevo fatto le routes, prendete spunto: https://github.com/MindfulLearner/vite-boolfolio/blob/master/src/router.ts

esempio:
![Screenshot 2024-11-21 141522](https://github.com/user-attachments/assets/7a6da274-da87-41e3-9ed7-9e174606b2cd)
simile a:
![dwadwa](https://github.com/user-attachments/assets/29c5f999-e7b9-4a17-ae4e-811fa882b598)

**Comment by salvatore-impellizzeri** [comment]
Creato Header con Home e Lista Appartamenti. Inserito anche nel router Login e Registrazione che sono state anche completate
